### ISSUE TITLE
Domain name already taken

### ISSUE THREAD

**Issue by chrisandchris** [jonnyzzz/TeamCity.Virtual#38]
From time to time I run into the issue of having a domain already created:

```
agent@prodtestagent:~$ vagrant up 99b879d
Bringing machine 'default' up with 'libvirt' provider...
Name `f61a661addc9b31f_default` of domain about to create is already taken. Please try to run
`vagrant up` command again.
```

Running `virsh list` results in

```
virsh # list
 Id    Name                           State
----------------------------------------------------
 5     f61a661addc9b31f_default       running
```

But then destroying that domain and trying to `vagrant up` or even `vagrant destroy` results in the same error.

I mostly run into the issue if a test fails at an early stage (around vagrant up).

Anybody an idea what reason that has?

**Comment by prashant0493** [comment]
@chrisandchris 
Similar issue was discussed here [https://github.com/vagrant-libvirt/vagrant-libvirt/issues/293](Fedora infra issues)
Probably libvirt takes some time to shutdown your default domain name even after you `vagrant destroy`

I would suggest you to have alternative domain name by editing Vagrantfile with:

`config.vm.define "vagrant_default1" do |vagrant_default1|`

you can temporarily get away with your problem with alternative domain name until libvirt shuts down the domain.

**Comment by chrisandchris** [comment]
That does probably help, but does not solve the issue.

The issue ist, that I then have a running virtual instance which never shuts down. And I'm not willing to log into my agent and destroy or undefine that machine - it's automated software test not manual test :) . However, I hadn't had the issue for quite some time.
