### ISSUE TITLE
Script is not Copied into docker container

### ISSUE THREAD

**Issue by annymsMthd** [jonnyzzz/TeamCity.Virtual#41]
Looks like the generated script is not copied or linked into the docker container

**Comment by jonnyzzz** [comment]
Could you please provide some steps to reproduce

**Comment by Malinskiy** [comment]
@jonnyzzz Hey guys. I have the same problem when using docker image of teamcity agent and mounting - /var/run/docker.sock:/var/run/docker.sock as one of the supported methods of docker in docker for https://hub.docker.com/r/jetbrains/teamcity-agent/

If I use the privileged mode and nested docker instance - everything works as expected.

**Comment by ejb1123** [comment]
@Malinskiy Can you give a example of the command you used?

**Comment by Malinskiy** [comment]
@ejb1123 my problem was not related to TeamCity.Virtual plugin

**Comment by jonnyzzz** [comment]
I'll close this. Please free to reopen or post a new one if you have any issues with the plugin
