### ISSUE TITLE
Support Docker private images on docker hub

### ISSUE THREAD

**Issue by yaron-idan** [jonnyzzz/TeamCity.Virtual#52]
Is there a plan to support these types of images? Or is there already a way to pull those that I've missed?
Thanks,
Yaron.

**Comment by jonnyzzz** [comment]
Could you please elaborate what is missing now to have this feature
supported?

Best regards,
Eugene Petrenko

**Comment by Elufimov** [comment]
@yaron-idan are you talking about authorization?

**Comment by yaron-idan** [comment]
Indeed.
I'm guessing I could add a command line step before the pull command in which I run docker login but would prefer a way to authorize the plugin (using .dockercfg or similar methods).

**Comment by yaron-idan** [comment]
Since authenticating using docker login as a previous step/any other authentication method works for pulling private images, I'm gonna go ahead and close this issue.
